CREATE TABLE "ExplainCache" (
  "key"        TEXT NOT NULL PRIMARY KEY,
  "resultJson" TEXT NOT NULL,
  "hitCount"   INTEGER NOT NULL DEFAULT 1,
  "createdAt"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastUsedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
